using System.Collections.Generic;
using System.Text;

namespace DocumentView.Framework.Generator;

internal static class DdxEntryEmitter
{
    public static string Emit(DdxClassModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {model.ClassName}");
        sb.AppendLine("{");
        sb.AppendLine("    protected override System.Collections.Generic.List<DocumentView.Framework.MfcDocument.DdxEntry> BuildEntries()");
        sb.AppendLine("    {");
        sb.AppendLine("        return");
        sb.AppendLine("        [");

        foreach (var m in model.Members)
        {
            sb.AppendLine("            new DocumentView.Framework.MfcDocument.DdxEntry(");
            sb.AppendLine($"                MemberName:      \"{m.MemberName}\",");
            sb.AppendLine($"                MemberType:      typeof({m.MemberTypeFullName}),");
            sb.AppendLine($"                ControlName:     \"{m.ControlName}\",");

            if (m.ControlProperty is null)
                sb.AppendLine("                ControlProperty: null,");
            else
                sb.AppendLine($"                ControlProperty: \"{m.ControlProperty}\",");

            sb.AppendLine($"                Getter:          () => this.{m.MemberName},");

            if (m.CanWrite)
                sb.AppendLine($"                Setter:          v  => this.{m.MemberName} = ({m.MemberTypeFullName})v,");
            else
                sb.AppendLine("                Setter:          v  => { },");

            if (m.Validators.Count == 0)
            {
                sb.AppendLine("                Validators:      []),");
            }
            else
            {
                sb.AppendLine("                Validators:");
                sb.AppendLine("                [");
                foreach (var v in m.Validators)
                {
                    var ctorArgs = string.Join(", ", v.CtorArgs);
                    if (v.MessageValue is null)
                        sb.AppendLine($"                    new {v.AttributeTypeFullName}({ctorArgs}),");
                    else
                        sb.AppendLine($"                    new {v.AttributeTypeFullName}({ctorArgs}) {{ Message = \"{EscapeString(v.MessageValue)}\" }},");
                }
                sb.AppendLine("                ]),");
            }
        }

        sb.AppendLine("        ];");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string EscapeString(string s) =>
        s.Replace("\\", "\\\\")
         .Replace("\"", "\\\"")
         .Replace("\n", "\\n")
         .Replace("\r", "\\r");
}
